const SCALES = {
  borders: 'borders',
  borderWidths: 'borderWidths',
  colors: 'colors',
  radii: 'radii',
  sizes: 'sizes',
  space: 'space',
  transitions: 'transitions',
  shadows: 'shadows',
  zIndexes: 'zIndexes',
  fonts: 'fonts',
  fontSizes: 'fontSizes',
  fontWeights: 'fontWeights',
  lineHeights: 'lineHeights',
  letterSpacings: 'letterSpacings',
} as const

export const SCALES_MAP = {
  gap: SCALES.space,
  gridGap: SCALES.space,
  columnGap: SCALES.space,
  gridColumnGap: SCALES.space,
  rowGap: SCALES.space,
  gridRowGap: SCALES.space,
  inset: SCALES.space,
  insetBlock: SCALES.space,
  insetBlockEnd: SCALES.space,
  insetBlockStart: SCALES.space,
  insetInline: SCALES.space,
  insetInlineEnd: SCALES.space,
  insetInlineStart: SCALES.space,
  margin: SCALES.space,
  marginTop: SCALES.space,
  marginRight: SCALES.space,
  marginBottom: SCALES.space,
  marginLeft: SCALES.space,
  marginBlock: SCALES.space,
  marginBlockEnd: SCALES.space,
  marginBlockStart: SCALES.space,
  marginInline: SCALES.space,
  marginInlineEnd: SCALES.space,
  marginInlineStart: SCALES.space,
  padding: SCALES.space,
  paddingTop: SCALES.space,
  paddingRight: SCALES.space,
  paddingBottom: SCALES.space,
  paddingLeft: SCALES.space,
  paddingBlock: SCALES.space,
  paddingBlockEnd: SCALES.space,
  paddingBlockStart: SCALES.space,
  paddingInline: SCALES.space,
  paddingInlineEnd: SCALES.space,
  paddingInlineStart: SCALES.space,
  top: SCALES.space,
  right: SCALES.space,
  bottom: SCALES.space,
  left: SCALES.space,
  scrollMargin: SCALES.space,
  scrollMarginTop: SCALES.space,
  scrollMarginRight: SCALES.space,
  scrollMarginBottom: SCALES.space,
  scrollMarginLeft: SCALES.space,
  scrollMarginX: SCALES.space,
  scrollMarginY: SCALES.space,
  scrollMarginBlock: SCALES.space,
  scrollMarginBlockEnd: SCALES.space,
  scrollMarginBlockStart: SCALES.space,
  scrollMarginInline: SCALES.space,
  scrollMarginInlineEnd: SCALES.space,
  scrollMarginInlineStart: SCALES.space,
  scrollPadding: SCALES.space,
  scrollPaddingTop: SCALES.space,
  scrollPaddingRight: SCALES.space,
  scrollPaddingBottom: SCALES.space,
  scrollPaddingLeft: SCALES.space,
  scrollPaddingX: SCALES.space,
  scrollPaddingY: SCALES.space,
  scrollPaddingBlock: SCALES.space,
  scrollPaddingBlockEnd: SCALES.space,
  scrollPaddingBlockStart: SCALES.space,
  scrollPaddingInline: SCALES.space,
  scrollPaddingInlineEnd: SCALES.space,
  scrollPaddingInlineStart: SCALES.space,

  fontSize: SCALES.fontSizes,

  background: SCALES.colors,
  backgroundColor: SCALES.colors,
  backgroundImage: SCALES.colors,
  border: SCALES.borders,
  borderBlock: SCALES.borders,
  borderBlockEnd: SCALES.borders,
  borderBlockStart: SCALES.borders,
  borderBottom: SCALES.borders,
  borderBottomColor: SCALES.colors,
  borderColor: SCALES.colors,
  borderInline: SCALES.borders,
  borderInlineEnd: SCALES.borders,
  borderInlineStart: SCALES.borders,
  borderLeft: SCALES.borders,
  borderLeftColor: SCALES.colors,
  borderRight: SCALES.borders,
  borderRightColor: SCALES.colors,
  borderTop: SCALES.borders,
  borderTopColor: SCALES.colors,
  caretColor: SCALES.colors,
  color: SCALES.colors,
  columnRuleColor: SCALES.colors,
  fill: SCALES.colors,
  outlineColor: SCALES.colors,
  stroke: SCALES.colors,
  textDecorationColor: SCALES.colors,

  fontFamily: SCALES.fonts,

  fontWeight: SCALES.fontWeights,

  lineHeight: SCALES.lineHeights,

  letterSpacing: SCALES.letterSpacings,

  blockSize: SCALES.sizes,
  minBlockSize: SCALES.sizes,
  maxBlockSize: SCALES.sizes,
  inlineSize: SCALES.sizes,
  minInlineSize: SCALES.sizes,
  maxInlineSize: SCALES.sizes,
  width: SCALES.sizes,
  minWidth: SCALES.sizes,
  maxWidth: SCALES.sizes,
  height: SCALES.sizes,
  minHeight: SCALES.sizes,
  maxHeight: SCALES.sizes,
  flexBasis: SCALES.sizes,

  borderWidth: SCALES.borderWidths,
  borderTopWidth: SCALES.borderWidths,
  borderRightWidth: SCALES.borderWidths,
  borderBottomWidth: SCALES.borderWidths,
  borderLeftWidth: SCALES.borderWidths,

  borderStyle: SCALES.borders,
  borderTopStyle: SCALES.borders,
  borderRightStyle: SCALES.borders,
  borderBottomStyle: SCALES.borders,
  borderLeftStyle: SCALES.borders,

  borderRadius: SCALES.radii,
  borderTopLeftRadius: SCALES.radii,
  borderTopRightRadius: SCALES.radii,
  borderBottomRightRadius: SCALES.radii,
  borderBottomLeftRadius: SCALES.radii,

  boxShadow: SCALES.shadows,
  textShadow: SCALES.shadows,

  transition: SCALES.transitions,

  zIndex: SCALES.zIndexes,
} as const
